// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CareateUserFoodRecord { moh_food_id: number, moh_unit_id: number, amount: number, order_index: number, filter: string, eat_datetime: string, }