// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DietPreference = "Vegetarian" | "Vegan" | "GlutenFree" | "Paleo" | "Keto" | "Pescatarian" | "LowCarb" | "HighProtein" | "Mediterranean" | "DairyFree" | "NutFree" | "Halal" | "Kosher";