// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DietPreference } from "./DietPreference";
import type { MedicalCondition } from "./MedicalCondition";
import type { UserFoodRecord } from "./UserFoodRecord";
import type { UserPhysicalMetrics } from "./UserPhysicalMetrics";

export interface FitnessUserData { owner_id: string, user_eat_history: Array<UserFoodRecord>, physical_metrics_history: Array<UserPhysicalMetrics>, diet_preferences: Array<DietPreference>, medical_conditions: Array<MedicalCondition>, }