// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TotalsUserEated } from "./TotalsUserEated";

export type HashMapUserEatedFood = Record<string, TotalsUserEated>;