// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoodsType } from "./FoodsType";

export interface Meal { id: string, name: string, datetime: string, duration: number, user_id: string, foods_eated: FoodsType, description: string, }