// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SammeryUserEated { day_average_food_energy: number, day_average_protein: number, }