// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TempMeal { id: string, name: string, datetime: string, duration: string, user_id: string, foods_eated: string, description: string, }
// TODO: duration is duration type