// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TotalsUserEated { total_food_energy: number, total_protein: number, total_carbohydrates: number, total_alcohol: number, total_total_fat: number, total_total_sugars: number, total_dietary_fiber: number, total_energy: number, }