// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export interface User { id: {Id: string, tb: string} | null | string, first_name: string | null, last_name: string | null, user_name: string, pass: string, role: Role, email: string, }