// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserFoodRecord { id: {Id: string, tb: string} | null | string, moh_food_id: number | null, moh_unit_id: number, amount: number, order_index: number, filter: string, eat_datetime: string, new: boolean | null, user_id: {Id: string, tb: string} | null | string, }