// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFoodRecordVec } from "./UserFoodRecordVec";
import type { UserMeal } from "./UserMeal";

export interface UserMealBuilder { ingredients: UserFoodRecordVec, meal: UserMeal, }