// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFoodRecord } from "./UserFoodRecord";

export type UserFoodRecordVec = Array<UserFoodRecord>;