// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashMapUserEatedFood } from "./HashMapUserEatedFood";
import type { SammeryUserEated } from "./SammeryUserEated";
import type { UserEatedFoodVec } from "./UserEatedFoodVec";

export interface UserEated { foods: UserEatedFoodVec, totals: HashMapUserEatedFood, last_date: string, averages: SammeryUserEated, macro_precentages: Record<string, number>, }