// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserMeal { id: string, name: string, eat_datetime: Date, duration: string, user_id: string, description: string, ingredients: string, }