// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserPhysicalMetrics { activity_level: string, dri: string, height: number, weight: number, neck_circumference: number | null, waist_circumference: number | null, hip_circumference: number | null, goal: string, created_at: string, updated_at: string, user_id: number, }