// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFoodRecord } from "./UserFoodRecord";
import type { UserPhysicalMetrics } from "./UserPhysicalMetrics";

export interface UserData { timezone: string, foods_history: Array<UserFoodRecord>, physical_metrics: UserPhysicalMetrics | null, }