// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AdditionalInfo { tarich_ptiha: string | null, tarich_idkun: string | null, makor: number | null, }