// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BasicInfo { index: number, moh_ingredient_unit_id: number, moh_food_id: number, hebrew_name: string, english_name: string, edible: number | null, psolet: number | null, water_loss_precentage: number | null, }