// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IngredientUnitWithName { moh_unit_id: number, moh_ingredient_unit_id: number, name: string, weight: number, }