// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdditionalInfo } from "./AdditionalInfo";
import type { AminoAcids } from "./AminoAcids";
import type { BasicInfo } from "./BasicInfo";
import type { FattyAcids } from "./FattyAcids";
import type { IngredientUnitWithName } from "./IngredientUnitWithName";
import type { Macronutrients } from "./Macronutrients";
import type { Minerals } from "./Minerals";
import type { Vitamins } from "./Vitamins";

export interface Ingredient { basic_info: BasicInfo, macronutrients: Macronutrients, vitamins: Vitamins, minerals: Minerals, fatty_acids: FattyAcids, amino_acids: AminoAcids, additional_info: AdditionalInfo, units: Array<IngredientUnitWithName>, }