// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitDefault { weight: number, unit_amount: number, unit_name: string, unit_id: number, }