// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ingredient } from "./Ingredient";
import type { UnitDefault } from "./UnitDefault";

export interface VecIngredients { ingredients: Array<Ingredient>, unit_default: UnitDefault, fields: Record<string, any>, }