import z from "zod";
import { type KeysOfNumberOrStringProps } from "../utileTypes";

const numNullable = z.number().nullable().or(z.string().nullable());
export type numNullableType = z.infer<typeof numNullable>;

export const mohIngredient = z.object({
    _id: z.number(),
    Code: z.number(),
    smlmitzrach: z.number(),
    shmmitzrach: z.string(),
    makor: numNullable,
    edible: numNullable,
    psolet: numNullable,
    ahuz_ibud_nozlim: numNullable,
    protein: numNullable,
    total_fat: numNullable,
    carbohydrates: numNullable,
    food_energy: numNullable,
    alcohol: numNullable,
    moisture: numNullable,
    total_dietary_fiber: numNullable,
    calcium: numNullable,
    iron: numNullable,
    magnesium: numNullable,
    phosphorus: numNullable,
    potassium: numNullable,
    sodium: numNullable,
    zinc: numNullable,
    copper: numNullable,
    vitamin_a_iu: numNullable,
    carotene: numNullable,
    vitamin_e: numNullable,
    vitamin_c: numNullable,
    thiamin: numNullable,
    riboflavin: numNullable,
    niacin: numNullable,
    vitamin_b6: numNullable,
    folate: numNullable,
    folate_dfe: z.string(),
    vitamin_b12: numNullable,
    cholesterol: numNullable,
    saturated_fat: numNullable,
    butyric: numNullable,
    caproic: numNullable,
    caprylic: numNullable,
    capric: numNullable,
    lauric: numNullable,
    myristic: numNullable,
    palmitic: numNullable,
    stearic: numNullable,
    oleic: numNullable,
    linoleic: numNullable,
    linolenic: numNullable,
    arachidonic: numNullable,
    docosahexanoic: numNullable,
    palmitoleic: numNullable,
    parinaric: numNullable,
    gadoleic: numNullable,
    eicosapentaenoic: numNullable,
    erucic: numNullable,
    docosapentaenoic: numNullable,
    mono_unsaturated_fat: numNullable,
    poly_unsaturated_fat: numNullable,
    vitamin_d: numNullable,
    total_sugars: numNullable,
    trans_fatty_acids: numNullable,
    vitamin_a_re: numNullable,
    isoleucine: numNullable,
    leucine: numNullable,
    valine: numNullable,
    lysine: numNullable,
    threonine: numNullable,
    methionine: numNullable,
    phenylalanine: numNullable,
    tryptophan: numNullable,
    histidine: numNullable,
    tyrosine: numNullable,
    arginine: numNullable,
    cystine: numNullable,
    serine: numNullable,
    vitamin_k: numNullable,
    pantothenic_acid: numNullable,
    iodine: numNullable,
    selenium: numNullable,
    sugar_alcohols: numNullable,
    choline: numNullable,
    biotin: numNullable,
    manganese: numNullable,
    fructose: numNullable,
    tarich_ptiha: z.string(),
    tarich_idkun: z.string(),
    english_name: z.string(),
});

export const mohUnit = z.object({
    "_id": z.number(),
    "smlmida": z.string().max(30),
    "shmmida": z.string().max(30),
    "englishName": z.string().max(30)
});

export const mohUnitsIngredient = z.object({
    "_id": z.number(),
    "mmitzrach": z.string().max(30),
    "mida": z.string().max(30),
    "mishkal": z.string().max(30),
});

export const UnitsFoodSchema = mohUnitsIngredient.merge(mohUnit);

export const FoodSchema = mohIngredient.extend({units: UnitsFoodSchema.array()});

export const FoodSchemaArray = FoodSchema.array();
export type FoodSchemaArrayType = z.infer<typeof FoodSchemaArray>;
export type FoodSchemaType = z.infer<typeof FoodSchema>;

export type KeysOfNumberOrStringPropsFields = KeysOfNumberOrStringProps<FoodSchemaType>;

export type IngredientFields = {
    [K in KeysOfNumberOrStringPropsFields]: {
        description: string,
        field: K,
        id: number,
        title: string,
        unit: string
    }
}

export const FoodGroupSchema = z.object({
    mohUniqueId: z.number(),
    name: z.string().min(2).max(50),
    foodGroup: z.string().min(20).max(150),
});

export const keysFoodGroupSchema: readonly (keyof Partial<FoodSchemaType>)[] = [
    "_id",
    "Code",
    "smlmitzrach",
    "shmmitzrach",
    "makor",
    "edible",
    "psolet",
    "ahuz_ibud_nozlim",
    "protein",
    "total_fat",
    "carbohydrates",
    "food_energy",
    "alcohol",
    "moisture",
    "total_dietary_fiber",
    "calcium",
    "iron",
    "magnesium",
    "phosphorus",
    "potassium",
    "sodium",
    "zinc",
    "copper",
    "vitamin_a_iu",
    "carotene",
    "vitamin_e",
    "vitamin_c",
    "thiamin",
    "riboflavin",
    "niacin",
    "vitamin_b6",
    "folate",
    "folate_dfe",
    "vitamin_b12",
    "cholesterol",
    "saturated_fat",
    "butyric",
    "caproic",
    "caprylic",
    "capric",
    "lauric",
    "myristic",
    "palmitic",
    "stearic",
    "oleic",
    "linoleic",
    "linolenic",
    "arachidonic",
    "docosahexanoic",
    "palmitoleic",
    "parinaric",
    "gadoleic",
    "eicosapentaenoic",
    "erucic",
    "docosapentaenoic",
    "mono_unsaturated_fat",
    "poly_unsaturated_fat",
    "vitamin_d",
    "total_sugars",
    "trans_fatty_acids",
    "vitamin_a_re",
    "isoleucine",
    "leucine",
    "valine",
    "lysine",
    "threonine",
    "methionine",
    "phenylalanine",
    "tryptophan",
    "histidine",
    "tyrosine",
    "arginine",
    "cystine",
    "serine",
    "vitamin_k",
    "pantothenic_acid",
    "iodine",
    "selenium",
    "sugar_alcohols",
    "choline",
    "biotin",
    "manganese",
    "fructose",
    "tarich_ptiha",
    "tarich_idkun",
    "english_name",
  ] as const;


export const onlyNutri = [
    "protein",
    "total_fat",
    "carbohydrates",
    "food_energy",
    "alcohol",
    "moisture",
    "total_dietary_fiber",
    "calcium",
    "iron",
    "magnesium",
    "phosphorus",
    "potassium",
    "sodium",
    "zinc",
    "copper",
    "vitamin_a_iu",
    "carotene",
    "vitamin_e",
    "vitamin_c",
    "thiamin",
    "riboflavin",
    "niacin",
    "vitamin_b6",
    "folate",
    "folate_dfe",
    "vitamin_b12",
    "cholesterol",
    "saturated_fat",
    "butyric",
    "caproic",
    "caprylic",
    "capric",
    "lauric",
    "myristic",
    "palmitic",
    "stearic",
    "oleic",
    "linoleic",
    "linolenic",
    "arachidonic",
    "docosahexanoic",
    "palmitoleic",
    "parinaric",
    "gadoleic",
    "eicosapentaenoic",
    "erucic",
    "docosapentaenoic",
    "mono_unsaturated_fat",
    "poly_unsaturated_fat",
    "vitamin_d",
    "total_sugars",
    "trans_fatty_acids",
    "vitamin_a_re",
    "isoleucine",
    "leucine",
    "valine",
    "lysine",
    "threonine",
    "methionine",
    "phenylalanine",
    "tryptophan",
    "histidine",
    "tyrosine",
    "arginine",
    "cystine",
    "serine",
    "vitamin_k",
    "pantothenic_acid",
    "iodine",
    "selenium",
    "sugar_alcohols",
    "choline",
    "biotin",
    "manganese",
    "fructose",
  ] as const;

  export type OnlyNutriType = KeysOfNumberOrStringPropsFields & typeof onlyNutri[number];

